files:
  - source: /AuthenticatorShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
    translation: /AuthenticatorShared/UI/Platform/Application/Support/Localizations/%two_letters_code%.lproj/%original_file_name%
